export const RESOLUTION_CODES = {
  STEP_CORRECT: 'PC',
  RESULT_CORRECT: 'RC',
  MORE_SOLUTIONS: 'MS',
  PENDING_FINISH: 'PF',
  RESOLUTION_FINISHED: 'RT',
  STEP_INCORRECT: 'PI',
  RESULT_INCORRECT: 'RI',
  RESULT_REPEATED: 'RR',
  SYNTAX_INCORRECT: 'SI',
  NO_SOLUTION: 'SS',
  FIRST_WARNING: 'PA',
  STEP_REPEATED: 'PR',
} as const;

export type ResolutionCode = (typeof RESOLUTION_CODES)[keyof typeof RESOLUTION_CODES];

export const RESOLUTION_STEP_NO_BRANCH = 1;
export const RESOLUTION_STEP_BRANCH = 2;
export const RESOLUTION_STEP_FINISH_ATTEMPT = 3;
export const RESOLUTION_STEP_INVALID_SUBEQUATION_ATTEMPT = 4;
export const EMPTY_SET = '{}';

export const NO_BIFURCO_RESOLUCION = RESOLUTION_STEP_NO_BRANCH;
export const BIFURCO_RESOLUCION = RESOLUTION_STEP_BRANCH;
export const CONJUNTO_VACIO = EMPTY_SET;
